// This model was generated by Lumber. However, you remain in control of your models.

const { upsignonError } = require("../helpers/preventCRUD");

// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Migrations = sequelize.define(
    "migrations",
    {
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      migrationTime: {
        type: DataTypes.DATE,
        defaultValue: Sequelize.literal("CURRENT_TIMESTAMP(0)"),
      },
    },
    {
      tableName: "migrations",
      underscored: true,
      timestamps: false,
      schema: process.env.DATABASE_SCHEMA,
    }
  );
  Migrations.removeAttribute("id");
  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Migrations.associate = (models) => {};

  Migrations.beforeBulkCreate(upsignonError);
  Migrations.beforeBulkDestroy(upsignonError);
  Migrations.beforeBulkUpdate(upsignonError);
  Migrations.beforeCreate(upsignonError);
  Migrations.beforeDestroy(upsignonError);
  Migrations.beforeUpdate(upsignonError);
  Migrations.beforeSave(upsignonError);
  Migrations.beforeUpsert(upsignonError);

  return Migrations;
};
