// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const UrlList = sequelize.define(
    "urlList",
    {
      displayedName: {
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true,
      },
      signinUrl: {
        type: DataTypes.STRING,
        validate: {
          isUrl: true,
        },
      },
      passwordChangeUrl: {
        type: DataTypes.STRING,
        validate: {
          isUrl: true,
        },
      },
    },
    {
      tableName: "url_list",
      underscored: true,
      timestamps: false,
      schema: process.env.DATABASE_SCHEMA,
    }
  );
  UrlList.removeAttribute("id");
  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  UrlList.associate = (models) => {};

  return UrlList;
};
