// This model was generated by Lumber. However, you remain in control of your models.
const { upsignonError } = require("../helpers/preventCRUD");

// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const UserDevices = sequelize.define(
    "userDevices",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
      },
      deviceName: {
        type: DataTypes.STRING,
      },
      deviceType: {
        type: DataTypes.STRING,
      },
      osVersion: {
        type: DataTypes.STRING,
      },
      appVersion: {
        type: DataTypes.STRING,
      },
      deviceUniqueId: {
        type: DataTypes.UUIDV4,
      },
      accessCodeHash: {
        type: DataTypes.STRING,
      },
      authorizationStatus: {
        type: DataTypes.ENUM(["AUTHORIZED", "PENDING", "REVOKED_BY_USER"]),
      },
      authorizationCode: {
        type: DataTypes.UUID,
      },
      authCodeExpirationDate: {
        type: DataTypes.DATE,
      },
      createdAt: {
        type: DataTypes.DATE,
        defaultValue: Sequelize.literal("CURRENT_TIMESTAMP(0)"),
      },
      revocationDate: {
        type: DataTypes.DATE,
      },
    },
    {
      tableName: "user_devices",
      underscored: true,
      timestamps: false,
      schema: process.env.DATABASE_SCHEMA,
    }
  );

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  UserDevices.associate = (models) => {
    UserDevices.belongsTo(models.users, {
      foreignKey: {
        name: "userIdKey",
        field: "user_id",
      },
      targetKey: "id",
      as: "user",
    });
    UserDevices.hasOne(models.passwordResetRequest, {
      foreignKey: "device_id",
      sourceKey: "id",
      as: "passwordResetRequest",
      onDelete: "CASCADE",
      hooks: true,
    });
    UserDevices.hasMany(models.usageLogs, {
      foreignKey: "device_id",
      sourceKey: "id",
      as: "logs",
      onDelete: "CASCADE",
      hooks: true,
    });
  };

  const authorizeOnlyDeviceNameEdition = (instance) => {
    const authorizedFields = ["deviceName"];
    const changedFields = Object.keys(instance._changed);
    changedFields.forEach((f) => {
      if (!authorizedFields.includes(f)) throw new Error("Only deviceName can be edited.");
    });
  };
  UserDevices.beforeBulkCreate(upsignonError);
  // UserDevices.beforeBulkDestroy(upsignonError);
  // UserDevices.beforeBulkUpdate(upsignonError);
  UserDevices.beforeCreate(upsignonError);
  // UserDevices.beforeDestroy(upsignonError);
  UserDevices.beforeUpdate(authorizeOnlyDeviceNameEdition);
  UserDevices.beforeSave(authorizeOnlyDeviceNameEdition);
  UserDevices.beforeUpsert(upsignonError);

  return UserDevices;
};
